spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    host: 192.168.30.132
    password: root
    port: 6379
    timeout: 20000
    #jedis连接池
    max-idle: 10
    min-idle: 5